name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ci_cd_tp
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - name: Lint code
        run: npx eslint src/

      - name: Wait for DB
        run: |
          sleep 20

      - name: Seed Database
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: password
          DB_NAME: ci_cd_tp
        run: node fixtures/seed.js

      - name: Run Unit Tests
        run: npx jest

      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          start: node src/app.js
          wait-on: http://localhost:3000
          wait-on-timeout: 60
        env:
          DB_HOST: 127.0.0.1
          DB_USER: root
          DB_PASSWORD: password
          DB_NAME: ci_cd_tp
